export const Questions = [
  {
    prompt: "Which part of a computer is used for typing?",
    optionA: "CPU",
    optionB: "Monitor",
    optionC: "Mouse",
    optionD: "Keyboard",
    answer: "optionD",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    answer: "optionC",
  },
  {
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    answer: "optionD",
  },
  {
    prompt: "Rolex is a company that specializes in what type of product?",
    optionA: "Watches",
    optionB: "Food",
    optionC: "Cosmetics",
    optionD: "Phone",
    answer: "optionA",
  },
  {
    prompt: "When did the website `Facebook` launch?",
    optionA: "2005",
    optionB: "2004",
    optionC: "2003",
    optionD: "2002",
    answer: "optionB",
  },
  {
    prompt: "Who played the character of harry potter in movie?",
    optionA: "Leonardo Di Caprio",
    optionB: "Daniel Red Cliff",
    optionC: "Denzel Washington",
    optionD: "Johnny Deep",
    answer: "optionB",
  },
];
